### ISSUE TITLE
Exception Thrown when calling 'search_youtube'

### ISSUE THREAD

**Issue by NeonDaniel** [HelloChatterbox/youtube_searcher#6]
Traceback below; looks like youtube results page can no longer be scraped the way it could be previously.

Traceback (most recent call last):
  File "/home/d_mcknight/.config/JetBrains/PyCharmCE2020.2/scratches/scratch_26.py", line 3, in <module>
    results = search_youtube("music")
  File "/home/d_mcknight/PycharmProjects/youtube_searcher/youtube_searcher/__init__.py", line 28, in search_youtube
    json_text = blob.split(s)[1].split(e)[0]
IndexError: list index out of range

**Comment by NeonDaniel** [comment]
It looks like this alternative is working:

https://github.com/AIIX/youtube-skill/commit/c9a45e6462fb7260b634e7c72ca8a7946af586d6#diff-fe0a1872386e063c8469b18ac0060093e3546f43e26b2039342aa2e467764a5e

**Comment by JarbasAl** [comment]
fixed in https://github.com/HelloChatterbox/youtube_searcher/commit/adda440fda38eb3cba9725ffea2d78884afb9758

thanks for pointing this out!

its published as v 0.1.3
